# Generated by Django 5.1.2 on 2024-10-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="category",
            field=models.CharField(
                choices=[
                    ("food", "Food"),
                    ("entertainment", "Entertainment"),
                    ("utilities", "Utilities"),
                    ("others", "Others"),
                ],
                default="others",
                max_length=50,
            ),
        ),
    ]
